import { KeralaDistrict, ExperienceLevel } from '../../types';

export const KERALA_DISTRICTS: KeralaDistrict[] = [
  'Thiruvananthapuram',
  'Kollam',
  'Pathanamthitta',
  'Alappuzha',
  'Kottayam',
  'Idukki',
  'Ernakulam',
  'Thrissur',
  'Palakkad',
  'Malappuram',
  'Kozhikode',
  'Wayanad',
  'Kannur',
  'Kasaragod',
];

export const TALENT_CATEGORIES = [
  'Actor',
  'Actress',
  'Child Artist',
  'Teen Artist',
  'Junior Artist',
  'Supporting Artist',
  'Character Artist',
  'Senior Artist',
  'Theatre Artist',
  'Model',
  'Dancer',
  'Singer',
  'Voice Artist',
  'Anchor',
  'Presenter',
  'Comedian',
  'Mimicry Artist',
  'Stunt Performer',
  'Background Artist',
];

export const EXPERIENCE_LEVELS: { label: string; value: ExperienceLevel }[] = [
  { label: 'Fresher / New Comer', value: 'fresher' },
  { label: 'Junior Artist', value: 'junior_artist' },
  { label: 'Experienced Actor', value: 'experienced' },
  { label: 'Working Actor', value: 'working_actor' },
  { label: 'Theatre Artist', value: 'theatre_actor' },
  { label: 'Senior Artist', value: 'senior_artist' },
  { label: 'Child Artist', value: 'child_artist' },
  { label: 'Teen Artist', value: 'teen_artist' },
  { label: 'Professional / Industry Lead', value: 'professional' },
];

export const AGE_PRESET_RANGES = [
  { label: '0–5 yrs (Infant / Toddler)', min: 0, max: 5 },
  { label: '6–10 yrs (Child Artist)', min: 6, max: 10 },
  { label: '11–15 yrs (Early Teen)', min: 11, max: 15 },
  { label: '16–20 yrs (Teen / Youth)', min: 16, max: 20 },
  { label: '21–30 yrs (Young Adult / Lead)', min: 21, max: 30 },
  { label: '31–40 yrs (Prime Actor)', min: 31, max: 40 },
  { label: '41–50 yrs (Character / Mature)', min: 41, max: 50 },
  { label: '51–60 yrs (Veteran / Senior)', min: 51, max: 60 },
  { label: '60+ yrs (Elders)', min: 60, max: 90 },
];

export const LANGUAGES_LIST = [
  'Malayalam (Native)',
  'Malayalam (Fluent)',
  'Tamil',
  'English',
  'Hindi',
  'Telugu',
  'Kannada',
  'Arabic',
  'Kochi Slang',
  'Malabar Slang',
  'Travancore Slang',
  'Thrissur Slang',
  'Valluvanadan Slang',
];

export const SKILLS_LIST = [
  'Kalaripayattu',
  'Classical Dance (Mohiniyattam/Bharatanatyam)',
  'Kathakali',
  'Contemporary Dance',
  'Folk Dance',
  'Martial Arts / Karate',
  'Two-Wheeler Driving',
  'Four-Wheeler Driving',
  'Heavy Vehicle Driving',
  'Swimming',
  'Voice Dubbing',
  'Mimicry',
  'Carnatic Singing',
  'Playback Singing',
  'Horse Riding',
  'Stage Combat',
  'Accents & Dialects',
  'Instrumental Music',
];

export const VENDOR_CATEGORIES = [
  'Camera Rental',
  'Lens Rental',
  'Lighting',
  'Grip',
  'Sound',
  'Drone',
  'Generator',
  'Vanity Van',
  'Caravan',
  'Transport',
  'Catering',
  'Accommodation',
  'Makeup',
  'Hair',
  'Costume',
  'Art Department',
  'Cinematographer',
  'Editor',
  'Colorist',
  'Sound Designer',
  'VFX',
  'Choreographer',
  'Stunt Team',
  'Props',
  'Set Construction',
  'Junior Artist Agency',
  'Security',
  'Production Assistance',
  'Location Services',
  'Other',
];

export const LOCATION_CATEGORIES = [
  'Traditional Kerala House',
  'Nalukettu',
  'Villa',
  'Modern Apartment',
  'House',
  'Tea Estate / Plantation',
  'Beach Property',
  'Hill Property',
  'Resort',
  'Hotel',
  'Office',
  'Hospital',
  'School / College',
  'Warehouse / Factory',
  'Shop / Market',
  'Farm',
  'Industrial Plant',
  'Private Property',
  'Other',
];

export const SUSPICIOUS_SAFETY_PHRASES = [
  'registration fee',
  'audition fee',
  'deposit',
  'payment before selection',
  'processing charge',
  'advance payment',
  'card fee',
  'portfolio charge',
  'cash transfer',
  'gpay deposit',
];

export const PRODUCTION_ROLES = [
  { value: 'director', label: 'Film / Serial Director' },
  { value: 'producer', label: 'Producer / Banner' },
  { value: 'casting_director', label: 'Casting Director' },
  { value: 'production_controller', label: 'Production Controller' },
  { value: 'production_manager', label: 'Production Manager' },
  { value: 'assistant_director', label: 'Chief / Assistant Director' },
];
